### ISSUE TITLE
Weak test `TestColumnInvalid`

### ISSUE THREAD

**Issue by mxgc** [bitfield/tpg-tools#2]
The test `TestColumnInvalid` would not pass if we change `p := pipeline.FromString("")` to `p := pipeline.FromString("1 2 3\n 1 2 3\n")`. (page 178 of the pdf) 

We need to return `p` after setting `p.Error` since the index for `fields[col-1]` would not be valid. (Listing 10.5)

Thank you for producing all those wonderful books about Go and showing what tasteful programs look like!

**Comment by bitfield** [comment]
Good spotting @mxgc! Thanks.
